from torchstain.tf.normalizers.macenko import TensorFlowMacenkoNormalizer
from torchstain.tf.normalizers.reinhard import TensorFlowReinhardNormalizer
from torchstain.tf.normalizers.multitarget import TensorFlowMultiMacenkoNormalizer
